export const chatActions = {
    LOGINREQUEST : 'LOGINREQUEST' ,
    LOGINFAILED : 'LOGINFAILED' ,
    LOGIN : 'LOGIN' ,
    LOGOUT : 'LOGOUT' ,
    MESSAGE : 'MESSAGE' ,
    MESSAGEREQUESTED : 'MESSAGEREQUESTED' ,
    MESSAGEFAILED : 'MESSAGEFAILED',
    MESSAGEPOSTREQUEST : 'MESSAGEPOSTREQUESTED' ,
    MESSAGEPOST : 'MESSAGEPOST' ,
    MESSAGEPOSTFAILED : "MESSAGEPOSTFAILED" ,
    USERSREQUEST : 'USERSREQUEST' ,
    USERS : 'USERS' ,
    USERSFAILED : 'USERSFAILED' ,
    USERREQUEST : 'USERREQUEST' ,
    USER : 'USER' ,
    USERFAILED : 'USERFAILED' ,

    CREATEMESSAGE : 'CREATEMESSAGE' ,
    CREATEMESSAGEREQUESTED : 'CREATEMESSAGEREQUESTED' ,
    CREATEMESSAGEFAILED : 'CREATEMESSAGEFAILED' ,

    STOREMESSAGE : 'STOREMESSAGE',
    STOREMESSAGEREQUEST : 'STOREMESSAGEREQUEST' ,
    STOREFAILED : 'STOREFAILED' ,

    ROOM : 'ROOM' ,

}