export const doctorActions = {
       // doctor
    DOCTORLOGIN : 'DOCTORLOGIN' , 
    DOCTORLOGINREQUEST: 'DOCTORLOGINREQUEST',
    DOCTORLOGINFAILED : 'DOCTORLOGINFAILED',
    DOCTORLOGOUT : 'DOCTORLOGOUT' ,
    TOTALCOUNTOFUSERSREQUEST : 'TOTALCOUNTOFUSERSREQUEST',
    TOTALCOUNTOFUSERS : 'TOTALCOUNTOFUSERS' ,
    TOTALCOUNTOFUSERSFAILED : 'TOTALCOUNTOFUSERSFAILED' ,
    APPOINTMENTS : 'APPOINTMENTS' ,
    APPOINTMENTSFAILED : 'APPOINTMENTSFAILED' ,
    APPOINTMENTSREQUEST : 'APPOINTMENTSREQUEST' ,
    CHANGESTATUSREQUEST : 'CHANGESTATUSREQUEST',
    TOTALPATIENTSREQUEST : 'TOTALPATIENTSREQUEST' ,
    TOTALPATIENTSFAILED : 'TOTALPATIENTSFAILED' ,
    TOTALPATIENTS : 'TOTALPATIENTS',

    DOCTORADDTIMEREQUEST : 'DOCTORADDTIMEREQUEST',
    DOCTORADDTIME : 'DOCTORADDTIME',
    DOCTORADDTIMEFAILED : 'DOCTORADDTIMEFAILED',

    DOCTORDATA : 'DOCTORDATA',
    DOCTORDATAREQUEST : 'DOCTORDATAREQUEST' ,
    DOCTORDATAFAILED : 'DOCTORDATAFAILED',

    DOCTORREVIEWREPLAY : 'DOCTORREVIEWREPLAY' ,
    DOCTORREVIEWREPLAYFAILED : 'DOCTORREVIEWREPLAYFAILED',
    DOCTORREVIEWREPLAYREQUESTED : 'DOCTORREVIEWREPLAYREQUESTED',

    DOCTOREDITREQUESTED : 'DOCTOREDITREQUESTED',
    DOCTOREDITFAILED:'DOCTOREDITFAILED' ,

    DOCTORCHANGEPASSWORD : 'DOCTORCHANGEPASSWORD' ,
    DOCTORCHANGEPASSWORDFAILED : 'DOCTORCHANGEPASSWORDFAILED' ,

    DOCTORPROFILEUPDATE : 'DOCTORPROFILEUPDATE' ,

    DOCTORFINDALLUSERMESSAGES : 'DOCTORFINDALLUSERMESSAGES',
    DOCTORFINDALLUSERMESSAGESREQUEST : 'DOCTORFINDALLUSERMESSAGESREQUEST',
    DOCTORFINDALLUSERMESSAGESFAILED : 'DOCTORFINDALLUSERMESSAGESFAILED'
    
}