export const userActions = {
    REGISTERREQUEST : 'registerrequest',
    REGISTERSUCCES : 'registersuccess',
    REGISTERFAILED : 'registerfailed',
    LOGINREQUEST : 'loginRequest',
    LOGINSUCCES : "loginSucces",
    LOGINFAILED : "loginFailed",
    LOGOUT : "logout",
    DOCTORFINDREQUEST : "doctorfindrequest",
    DOCTORFINDSUCCESS : "doctorfindsuccess",
    DOCTORFINDFAILED : "doctorfindfailed",
    SPECIALITYREQUEST : "specialityrequest",
    SPECIALITYSUCCESS : 'specialitysuccess',
    SPECIALITYFAILED : 'specialityFailed' ,
    SELECTEDDOCTORREQUEST : "selectedDctorRequest",
    SELCETEDDOCTORSUCCESS : 'slelectedDoctorSuccess',
    SELECTEDDOCTORFAILED : 'selectedDoctorFailed',
    USERFAVORITEDOCTORREQUEST : 'userfavoritedoctorrequest',
    USERFAVORITEDOCTORSUCCESS : 'userfavoritedoctorsuccess',
    USERFAVORIREDOCTORFAILED : 'userfavoritedoctorfailed',
    USERFAVORITEADDDOCTORREQUEST : 'userfavoritedoctoraddrequest',
    USERFAVORITEADDDOCTORSUCCESS : 'userfavoritedoctoraddsuccess',
    USERFAVORIREDOCTORADDFAILED : 'userfavoritedoctoraddfailed'
}